### ISSUE TITLE
Advantage over org-pretty-tags?

### ISSUE THREAD

**Issue by heikkil** [stardiviner/org-tag-beautify#2]
Could you elaborate in the README what advantages this package brings over org-pretty-tags?

You are using the icons from org-pretty-tags and the outcome seems to be pretty much the same. It is difficult, at first glance at least, to see what is the practical difference of your package to the user. If you have plans to take this further to do something org-pretty-tags does not do, it would be interesting to know.

Thanks!

**Comment by stardiviner** [comment]
Please read the readme. I said in there about this package.
